version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: electricity-bot-bd
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build:
      context: ./electricity-bot-backend
    container_name: electricity-bot-flask
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    env_file:
      - .env

volumes:
  mysql_data:
