"""add last_seen to DeviceModel

Revision ID: 2fa5685d8a7d
Revises: dd60fc5efb60
Create Date: 2025-05-31 17:10:13.271550

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fa5685d8a7d"
down_revision: Union[str, None] = "dd60fc5efb60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("devices", sa.Column("last_seen", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "last_seen")
    # ### end Alembic commands ###
