import os, smtplib, logging
from string import Template
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from premailer import transform
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)

SMTP_EMAIL = os.getenv("SMTP_EMAIL")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")

HTML_TMPL = Template(
    """
<table role="presentation" width="100%" cellpadding="0" cellspacing="0"
       style="background:#f4f7fd;padding:32px 0;font-family:'Segoe UI',Tahoma,sans-serif">
  <tr>
    <td align="center">
      <table role="presentation" cellpadding="0" cellspacing="0" width="640"
             style="background:#fff;border-radius:24px;padding:40px 32px;
                    box-shadow:0 10px 35px rgba(0,0,0,.07)">
        <tr><td align="center" style="font-size:64px;line-height:1">💡</td></tr>
        <tr><td align="center"
                style="font-size:28px;font-weight:600;color:#1f2f55;padding-top:8px">
            Welcome to Electricity Bot, ${first_name}!
        </td></tr>
        <tr><td style="font-size:17px;line-height:1.6;color:#2b2b2b;padding-top:24px">
            You’ve just joined <a href="https://bot-1.electricity-bot.online/" 
            style="color:#4285f4;font-weight:600;text-decoration:none">
            Electricity Bot</a> – your smart sidekick for when the lights go out.
        </td></tr>
        <tr><td style="font-size:14px;color:#777;padding-top:40px;text-align:center">
            ✨ No need to reply – this message was generated by a very smart basement ⚙️
        </td></tr>
      </table>
    </td>
  </tr>
</table>
"""
).substitute


def send_welcome_email(to_email: str, first_name: str = "friend") -> None:
    if not SMTP_EMAIL or not SMTP_PASSWORD:
        raise RuntimeError("SMTP_EMAIL / SMTP_PASSWORD не задані!")

    html_raw = HTML_TMPL(first_name=first_name)
    html_inline = transform(html_raw)

    text_part = MIMEText(
        f"Hi {first_name}! Welcome to Electricity Bot – your smart sidekick for "
        "blackouts.\n\n(No reply needed.)",
        "plain",
        "utf-8",
    )
    html_part = MIMEText(html_inline, "html", "utf-8")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = "💡 Welcome to Electricity Bot!"
    msg["From"] = SMTP_EMAIL
    msg["To"] = to_email
    msg.attach(text_part)
    msg.attach(html_part)

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(SMTP_EMAIL, SMTP_PASSWORD)
            server.send_message(msg)
        logger.info(f"[Email] sent to {to_email}")
    except Exception as exception:
        logger.error(f"[Email] ERROR → {exception}")
        raise
