"""init with varchar lengths

Revision ID: 7bdb0a68dcb0
Revises:
Create Date: 2025-06-11 00:43:33.443411

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7bdb0a68dcb0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("device_id", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("owner_email", sa.String(length=255), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("device_id"),
        sa.UniqueConstraint("owner_email"),
    )
    op.create_table(
        "measurements",
        sa.Column("measurement_id", sa.String(length=255), nullable=False),
        sa.Column("device_id", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("outgate_status", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("measurement_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("measurements")
    op.drop_table("devices")
    # ### end Alembic commands ###
