"""remove first_name and last_name from users

Revision ID: ed7c888fb1dc
Revises: 59d63476afcd
Create Date: 2025-06-17 17:42:58.093637

"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ed7c888fb1dc"
down_revision = "59d63476afcd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "first_name")
    op.drop_column("users", "last_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_name", mysql.VARCHAR(length=255), nullable=False)
    )
    op.add_column(
        "users", sa.Column("first_name", mysql.VARCHAR(length=255), nullable=False)
    )
    # ### end Alembic commands ###
