name: Backend CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:

  # Backend (Python) – lint with black
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install black
      - run: black --check backend/electricity-bot-backend