name: Fullstack CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:

  # Backend (Python) 
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install black
      - run: black --check .

  # Python tests (if exist)
  test-python:
    runs-on: ubuntu-latest
    needs: lint-python
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
      - name: Run tests if they exist
        run: |
          if [ -d "tests" ]; then
            pytest tests
          else
            echo "No tests yet"
          fi

  # Embedded ? Bash (ShellCheck)
  lint-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [ -d "embedded/bash" ]; then
            sudo apt-get update && sudo apt-get install -y shellcheck
            shellcheck embedded/bash/*.sh || true
          else
            echo "No bash scripts found"
          fi

  # Embedded ? C++ 
  build-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [ -f "embedded/cpp/main.cpp" ]; then
            g++ -o embedded/cpp/main embedded/cpp/main.cpp
          else
            echo "No C++ file found"
          fi

  # Frontend ?
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          if [ -f "frontend/package.json" ]; then
            cd frontend
            npm install
            npx eslint . || true
          else
            echo "No frontend found"
          fi

  # Frontend ?
  build-frontend:
    runs-on: ubuntu-latest
    needs: lint-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          if [ -f "frontend/package.json" ]; then
            cd frontend
            npm install
            npm run build || echo "Build script not found"
          else
            echo "No frontend found"
          fi

  # iOS SwiftUI 
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [ -d "app" ]; then
            echo "Building iOS app..."
            xcodebuild -scheme "YourAppScheme" -sdk iphonesimulator || echo "No Xcode project or scheme"
          else
            echo "No iOS app found"
          fi